services:
  - type: web
    name: sohibmulk-bot
    runtime: python
    build:
      environment: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "8317409742:AAG1Y_3ze0EGij1zADwrI4up9NNTmelq2ng"
      - key: TZ
        value: "Asia/Dushanbe"
